import json, os

base = "/Users/laurentickner/Desktop/sales-training-db"
appdata = os.path.join(base, "app-data")
out_dir = os.path.join(base, "app", "data")
os.makedirs(out_dir, exist_ok=True)

objections = json.load(open(os.path.join(appdata, "objection-responses.json")))
flags = json.load(open(os.path.join(appdata, "discovery-flags.json")))
funnel = json.load(open(os.path.join(appdata, "funnel-stages.json")))

bundle = (
    "// AUTO-GENERATED by build_app_data.py from app-data/*.json — do not edit by hand.\n"
    "// Regenerate after changing the source JSON.\n"
    "window.COPILOT_DATA = {\n"
    f"  objections: {json.dumps(objections, ensure_ascii=False)},\n"
    f"  discoveryFlags: {json.dumps(flags, ensure_ascii=False)},\n"
    f"  funnel: {json.dumps(funnel, ensure_ascii=False)}\n"
    "};\n"
)

with open(os.path.join(out_dir, "data.js"), "w") as f:
    f.write(bundle)

print(f"wrote app/data/data.js — {len(bundle)} bytes")
print(f"  {len(objections['objections'])} objections, {sum(len(o['triggers']) for o in objections['objections'])} objection triggers")
print(f"  {len(flags['flags'])} discovery flags, {sum(len(fl['triggers']) for fl in flags['flags'])} flag triggers")
print(f"  {len(funnel['stages'])} funnel stages")
