"""Build triage/data/data.js from triage-data/triage-data.json.

Also pulls the closer's app-data/objection-responses.json so the same 29
objection handlers (price, think-about-it, spouse, been-burned, etc.) fire
inside the triage tool. One source of truth — edit objections in app-data/
and both tools update on next rebuild.
"""
import json, os, sys

base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def need(cond, msg):
    if not cond:
        sys.exit("build_triage_data.py: VALIDATION FAILED — " + msg)


def load(rel_path):
    path = os.path.join(base, rel_path)
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        sys.exit("build_triage_data.py: missing " + path)
    except json.JSONDecodeError as e:
        sys.exit("build_triage_data.py: %s is not valid JSON — %s" % (rel_path, e))


def validate_triage(d):
    need("stages" in d, "missing top-level 'stages'")
    for i, s in enumerate(d["stages"]):
        for k in ("id", "name", "goal", "say", "green_light", "pushback_triggers", "pushback_script"):
            need(k in s, "stage #%d (%s) missing %s" % (i, s.get("id", "?"), k))


def validate_objections(d):
    need("objections" in d, "objection-responses.json missing 'objections' array")
    for i, o in enumerate(d["objections"]):
        for k in ("id", "label", "triggers", "response_steps"):
            need(k in o, "objection #%d (%s) missing %s" % (i, o.get("id", "?"), k))


data = load("triage-data/triage-data.json")
validate_triage(data)

objections_doc = load("app-data/objection-responses.json")
validate_objections(objections_doc)

# Attach the closer's objection bank to the triage bundle so triage/app.js
# can fire the same 29 objection cards. Stored under DATA.objections (the
# full doc, including universal_framework + situations).
data["objections"] = objections_doc

out_dir = os.path.join(base, "triage", "data")
os.makedirs(out_dir, exist_ok=True)

bundle = (
    "// AUTO-GENERATED by scripts/build_triage_data.py.\n"
    "// Source: triage-data/triage-data.json + app-data/objection-responses.json.\n"
    "// Do not edit by hand. Regenerate after editing the source JSON.\n"
    "window.TRIAGE_DATA = " + json.dumps(data, ensure_ascii=False) + ";\n"
)
with open(os.path.join(out_dir, "data.js"), "w", encoding="utf-8") as f:
    f.write(bundle)

print("wrote triage/data/data.js — %d bytes" % len(bundle))
print("  %d stages, %d global uncertainty signals, %d objections from closer" % (
    len(data["stages"]),
    len(data.get("uncertainty_globals", {}).get("signals", [])),
    len(objections_doc["objections"]),
))
for s in data["stages"]:
    print("  · %s (%d triggers)" % (s["name"], len(s["pushback_triggers"])))
