#!/usr/bin/env python3
"""Build app/data/data.js from app-data/*.json.

Validates the source JSON before writing so a malformed entry fails the build
loudly here instead of bricking the app on the first keystroke.
"""
import json
import os
import sys

base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
appdata = os.path.join(base, "app-data")
out_dir = os.path.join(base, "app", "data")

REQUIRED_OBJ = {"id", "bucket", "type", "label", "triggers", "response_steps", "source"}
REQUIRED_FLAG = {"id", "signal", "belief", "triggers", "probe", "note"}
REQUIRED_STAGE = {"id", "name", "goal", "listen_for", "advance_when"}
# A stage must have either `say` (a list) or `options` (a list of {title, lines}).


def die(msg):
    sys.exit("build_app_data.py: VALIDATION FAILED — " + msg)


def need(cond, msg):
    if not cond:
        die(msg)


def load(name):
    path = os.path.join(appdata, name)
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        sys.exit("build_app_data.py: missing " + path)
    except json.JSONDecodeError as e:
        sys.exit("build_app_data.py: " + name + " is not valid JSON — " + str(e))


def validate(objections, flags, funnel):
    need("objections" in objections, "objection-responses.json missing top-level 'objections'")
    need("universal_framework" in objections, "objection-responses.json missing 'universal_framework'")
    seen = set()
    trigger_owner = {}
    for i, o in enumerate(objections["objections"]):
        missing = REQUIRED_OBJ - o.keys()
        need(not missing, "objection #%d (%s) missing %s" % (i, o.get("id", "?"), missing))
        need(o["id"] not in seen, "duplicate objection id %s" % o["id"])
        seen.add(o["id"])
        need(isinstance(o["triggers"], list) and o["triggers"],
             "objection %s: empty/invalid triggers" % o["id"])
        need(isinstance(o["response_steps"], list) and o["response_steps"],
             "objection %s: empty response_steps" % o["id"])
        for t in o["triggers"]:
            if t in trigger_owner and trigger_owner[t] != o["id"]:
                print("WARN: trigger %r in both %s and %s" % (t, trigger_owner[t], o["id"]))
            trigger_owner[t] = o["id"]

    need("flags" in flags, "discovery-flags.json missing top-level 'flags'")
    fseen = set()
    for i, fl in enumerate(flags["flags"]):
        missing = REQUIRED_FLAG - fl.keys()
        need(not missing, "flag #%d (%s) missing %s" % (i, fl.get("id", "?"), missing))
        need(fl["id"] not in fseen, "duplicate flag id %s" % fl["id"])
        fseen.add(fl["id"])
        need(isinstance(fl["triggers"], list) and fl["triggers"],
             "flag %s: empty/invalid triggers" % fl["id"])

    need("stages" in funnel, "funnel-stages.json missing top-level 'stages'")
    for i, st in enumerate(funnel["stages"]):
        missing = REQUIRED_STAGE - st.keys()
        need(not missing, "stage #%d (%s) missing %s" % (i, st.get("id", "?"), missing))
        has_say = isinstance(st.get("say"), list) and st["say"]
        has_options = isinstance(st.get("options"), list) and st["options"]
        need(has_say or has_options,
             "stage %s: needs either 'say' (list) or 'options' (list)" % st["id"])


objections = load("objection-responses.json")
flags = load("discovery-flags.json")
funnel = load("funnel-stages.json")

validate(objections, flags, funnel)

os.makedirs(out_dir, exist_ok=True)
bundle = (
    "// AUTO-GENERATED by build_app_data.py from app-data/*.json — do not edit by hand.\n"
    "// Regenerate after changing the source JSON.\n"
    "window.COPILOT_DATA = {\n"
    "  objections: %s,\n" % json.dumps(objections, ensure_ascii=False)
    + "  discoveryFlags: %s,\n" % json.dumps(flags, ensure_ascii=False)
    + "  funnel: %s\n" % json.dumps(funnel, ensure_ascii=False)
    + "};\n"
)

with open(os.path.join(out_dir, "data.js"), "w", encoding="utf-8") as f:
    f.write(bundle)

print("wrote app/data/data.js — %d bytes" % len(bundle))
print("  %d objections, %d objection triggers"
      % (len(objections["objections"]),
         sum(len(o["triggers"]) for o in objections["objections"])))
print("  %d situations" % len(objections.get("situations", [])))
print("  %d discovery flags, %d flag triggers"
      % (len(flags["flags"]), sum(len(fl["triggers"]) for fl in flags["flags"])))
print("  %d funnel stages" % len(funnel["stages"]))
