"""Build triage/data/data.js from triage-data/triage-data.json.

Same pattern as build_app_data.py, but for the Triage Call Copilot.
"""
import json, os, sys

base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def need(cond, msg):
    if not cond:
        sys.exit("build_triage_data.py: VALIDATION FAILED — " + msg)


def load(name):
    path = os.path.join(base, "triage-data", name)
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        sys.exit("build_triage_data.py: missing " + path)
    except json.JSONDecodeError as e:
        sys.exit("build_triage_data.py: %s is not valid JSON — %s" % (name, e))


def validate(d):
    need("stages" in d, "missing top-level 'stages'")
    for i, s in enumerate(d["stages"]):
        for k in ("id", "name", "goal", "say", "green_light", "pushback_triggers", "pushback_script"):
            need(k in s, "stage #%d (%s) missing %s" % (i, s.get("id", "?"), k))


data = load("triage-data.json")
validate(data)

out_dir = os.path.join(base, "triage", "data")
os.makedirs(out_dir, exist_ok=True)

bundle = (
    "// AUTO-GENERATED by scripts/build_triage_data.py from triage-data/triage-data.json\n"
    "// Do not edit by hand. Regenerate after editing the source JSON.\n"
    "window.TRIAGE_DATA = " + json.dumps(data, ensure_ascii=False) + ";\n"
)
with open(os.path.join(out_dir, "data.js"), "w", encoding="utf-8") as f:
    f.write(bundle)

print("wrote triage/data/data.js — %d bytes" % len(bundle))
print("  %d stages, %d global uncertainty signals" % (
    len(data["stages"]),
    len(data.get("uncertainty_globals", {}).get("signals", []))
))
for s in data["stages"]:
    print("  · %s (%d triggers)" % (s["name"], len(s["pushback_triggers"])))
